# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager


controller_names:
  - hand_controller
  - arm_group_controller

hand_controller:
  type: GripperCommand
  joints:
    - arm_j6
  action_ns: gripper_cmd
  default: true
arm_group_controller:
  type: FollowJointTrajectory
  action_ns: follow_joint_trajectory
  default: true
  joints:
    - arm_j1
    - arm_j2
    - arm_j3
    - arm_j4
    - arm_j5