# MoveIt uses this configuration for controller management

trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  trajectory_duration_monitoring: true
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager



moveit_simple_controller_manager:
  controller_names:
    # - hand_controller
    - arm_group_controller

  # hand_controller:
  #   type: GripperCommand
  #   joints:
  #     - arm_j6
  #   action_ns: gripper_cmd
  #   default: true
  arm_group_controller:
    type: ForwardCommandController
    action_ns: forward_command_controller
    default: true
    joints:
      - arm_j1
      - arm_j2
      - arm_j3
      - arm_j4
      - arm_j5