controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    # hand_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController


    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# hand_controller:
#   ros__parameters:
#     joints: 
#       - arm_j6
#     command_interfaces:
#       - effort
#     state_interfaces:
#       - position
#       - velocity
arm_group_controller:
  ros__parameters:
    joints:
      - arm_j1
      - arm_j2
      - arm_j3
      - arm_j4
      - arm_j5
      # - arm_j6
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    open_loop_control: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
    gains:
      arm_j1:
        p: 1000.0
        i: 0.01
        d: 10.0
        i_clamp: 0.0
        ff_velocity_scale: 0.1
        normalize_error: true
      arm_j2:
        p: 100.0
        i: 0.01 
        d: 10.0
        i_clamp: 0.0
        ff_velocity_scale: 0.1
        normalize_error: true
      arm_j3:
        p: 100.0
        i: 0.01 
        d: 10.0
        i_clamp: 0.0
        ff_velocity_scale: 0.1
        normalize_error: true
      arm_j4:
        p: 100.0
        i: 0.01 
        d: 10.0
        i_clamp: 0.0
        ff_velocity_scale: 0.1
        normalize_error: true
      arm_j5:
        p: 100.0
        i: 0.01 
        d: 10.0  
        i_clamp: 0.0
        ff_velocity_scale: 0.1
        normalize_error: true
      # arm_j6:
      #   p: 100.0
      #   i: 0.01 
      #   d: 10.0  
      #   i_clamp: 0.0
      #   ff_velocity_scale: 0.1
      #   normalize_error: true
