controller_manager:
  ros__parameters:
    update_rate: 1000 # Hz

    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

hand_controller:
  ros__parameters:
    joints: 
      - arm_j6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
arm_group_controller:
  ros__parameters:
    joints:
      - arm_j1
      - arm_j2
      - arm_j3
      - arm_j4
      - arm_j5
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false

    # open_loop_control: false
    # allow_integration_in_goal_trajectory: true

    # gains:
    #     arm_j1:
    #       p: 2.0
    #       i: 1.0
    #       d: 1.0
    #       i_clamp: 1.0
    #       ff_velocity_scale: 2.0
    #     arm_j2:
    #       p: 2.0
    #       i: 1.0
    #       d: 1.0
    #       i_clamp: 1.0
    #       ff_velocity_scale: 2.0
    #     arm_j3:
    #       p: 2.0
    #       i: 1.0
    #       d: 1.0
    #       i_clamp: 1.0
    #       ff_velocity_scale: 2.0
    #     arm_j4:
    #       p: 2.0
    #       i: 1.0
    #       d: 1.0
    #       i_clamp: 1.0
    #       ff_velocity_scale: 2.0
    #     arm_j5:
    #       p: 2.0
    #       i: 1.0
    #       d: 1.0
    #       i_clamp: 1.0
    #       ff_velocity_scale: 2.0
    #     arm_j6:
    #       p: 2.0
    #       i: 1.0
    #       d: 1.0
    #       i_clamp: 1.0
    #       ff_velocity_scale: 2.0

    

  #   state_publish_rate: 50.0
  #   action_monitor_rate: 20.0
