controller_manager:
  ros__parameters:
    update_rate: 30 # Hz

    # hand_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController


    arm_group_controller:
      type: forward_command_controller/ForwardCommandController
      # type: joint_trajectory_controller/JointTrajectoryController

    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# hand_controller:
#   ros__parameters:
#     joints: 
#       - arm_j6
#     command_interfaces:
#       - effort
#     state_interfaces:
#       - position
#       - velocity
arm_group_controller:
  ros__parameters:
    joints:
      - arm_j1
      - arm_j2
      - arm_j3
      - arm_j4
      - arm_j5
      - arm_j6
      # - arm_j7
    interface_name: effort
