controller_manager:
  ros__parameters:
    update_rate: 300000000

    effort_controllers:
      type: effort_controllers/JointGroupEffortController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster  


effort_controllers:
  ros__parameters:
    publish_rate: 50.0

    joints:
      - arm_j1
      - arm_j2
      - arm_j3
      - arm_j4
      - arm_j5
      - arm_j6    
    command_interfaces:
       - efort
    state_interfaces:
       - position
       - velocity
       - effort
    

  # open_loop_control: false
  # allow_integration_in_goal_trajectory: true

  # gains:
  #     arm_j1:
  #       p: 2.0
  #       i: 1.0
  #       d: 1.0
  #       i_clamp: 1.0
  #       ff_velocity_scale: 2.0
    

  #   state_publish_rate: 50.0
  #   action_monitor_rate: 20.0