# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_group_controller:
  ros__parameters:
    joints:
      - arm_j1
      - arm_j2
      - arm_j3
      - arm_j4
      - arm_j5
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
hand_controller:
  ros__parameters:
    joint: arm_j6
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity